apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-extractor
  namespace: namespaceVar
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: text-extractor
      tier: dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: text-extractor
        tier: dev
    spec:
      # imagePullSecrets:
      #   - name: bhyveacrdev
      containers:
        - image: bhyveregistry.azurecr.io/text-extractor:latest
          imagePullPolicy: IfNotPresent
          name: text-extractor
          volumeMounts:
            - name: appdata
              mountPath: /appdata
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: TRANSFORMERS_CACHE
              value: "/appdata"
          resources:  # Add this section to define GPU resource request
            limits:
              nvidia.com/gpu: 1  # Request 1 NVIDIA GPU
              memory: 16Gi
            requests:
              nvidia.com/gpu: 1  # Require 1 NVIDIA GPU
              memory: 16Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: appdata
          persistentVolumeClaim:
            claimName: text-extractor-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: text-extractor-pvc
  namespace: bhyve-dev
spec:
  storageClassName: managed
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi